const USER_NAME_AND_PASSWORD_REQUIRED = "USER_NAME_AND_PASSWORD_REQUIRED";
const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
const USER_NOT_EXISTS = "USER_NOT_EXISTS";
const USERNAME_OR_PASSWORD_ERROR = "USERNAME_OR_PASSWORD_ERROR";
const TOKEN_EXPIRED = "TOKEN_EXPIRED";

module.exports = {
  USER_NAME_AND_PASSWORD_REQUIRED,
  USER_ALREADY_EXISTS,
  USER_NOT_EXISTS,
  USERNAME_OR_PASSWORD_ERROR,
  TOKEN_EXPIRED,
};
