const USER_NAME_AND_PASSWORD_REQUIRED = "USER_NAME_AND_PASSWORD_REQUIRED";
const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";

module.exports = { USER_NAME_AND_PASSWORD_REQUIRED, USER_ALREADY_EXISTS };
